== Приложение 2. Значения SW-кодов

Рутокен может возвращать следующие сочетания кодов SW1-SW2:

.Таблица кодов возврата
[%collapsible]
====
[cols=",,,",]
|===
|SW1 |Значение SW1 |SW2 |Значение SW2

|*0x90* |Команда выполнена успешно |*0x00* |Нет дополнительной
информации

|*0x63* +
 + |Неудачная аутентификация |*0x00* |Нет дополнительной информации

| | |*0xCX* |X – количество оставшихся попыток +
доступа к данному DO

|*0x64* |Состояние памяти токена не изменилось (неожиданный конец
файлового объекта или ошибка перед началом записи в память) |*0x00* |Нет
дополнительной информации

|*0x65* +
 + |Состояние памяти токена изменилось (ошибка в процессе записи в
память) +
 + |*0x00* |Нет дополнительной информации

| | |*0x81* |Повреждение памяти (memory failure)

|*0x67* |Неверная длина входного и/или выходного буфера (Lc и/или Le)
|*0x00* |Нет дополнительной информации

|*0x68* +
 +
 +
 + a|
Ошибка, связанная с информацией в байте CLA


|*0x81* |Логические каналы не поддерживаются

| | |*0x82* |Secure Messaging не поддерживается

| | |*0x83* |Ожидается завершающая команда цепочки +
(выдается при попытке выполнить другую команду +
до завершения цепочки команд)

| | |*0x84* |Цепочка команд не поддерживается

|*0x69* 
 + a|
Команда не позволена +
(command not allowed)

|*0x82* |Права доступа неудовлетворительны для выполнения команды (нет
прав для выполнения команды)

| | |*0x83* |Файловый объект заблокирован

| | |*0x84* |Референсные данные испорчены или неверные

| | |*0x85* |Непригодные условия выполнения команды +
(например, попытка удаления непустой папки)

| | |*0x86* |Нет текущего EF/RSF

| | |*0x87* |Отсутствует обязательный +
элемент данных (TLV-структура) Secure Messaging

| | |*0x88* |Недопустимый или некорректный +
элемент данных Secure Messaging

| | |*0x89* |Команда недопустима на данной стадии (фазе) +
жизненного цикла файлового объекта/карты

| | |*0x94* |Ключ шифрования не предназначен +
для выполнения данной операции

| | |*0x96* |Неверная ЭП или имитовставка +
(в командах PSO \| VCC и PSO \| VDS)

|*0x6A* |Неверные параметры команды |*0x80* |Неверные параметры
(данные) +
во входном буфере (в поле DATA)

| | |*0x81* |Затребованная функция этой команды +
не поддерживается

| | |*0x82* |Файловый объект не найден

| | |*0x84* |Недостаточно места в EEPROM-памяти токена

| | |*0x86* |Неверные параметры команды (P1-P2)

| | |*0x88* |Референсные данные не найдены

| | |*0x89* |Файловый объект уже существует

|*0x6B* |Заданное смещение – за границей двоичного файла |*0x00* |Нет
дополнительной информации

|*0x6C* |Неверная длина выходного буфера (Le) |*0xXX* |XX –
рекомендуемая точная длина выходного буфера

|*0x6D* |Неверная или неподдерживаемая команда |*0x00* |Нет
дополнительной информации

|*0x6E* |Неверное или неподдерживаемое значение CLA |*0x00* |Нет
дополнительной информации

|*0x6F* 
 + a|
Собственный класс ошибки 

|*0x01* |Токен имеет протокол обмена, не поддерживаемый +
USB-драйвером (более новый, чем в драйвере)

| | |*0x02* |Токен имеет аппаратную конфигурацию, +
отличную от ожидаемой

| | |*0x03* |Токен не поддерживает затребованный +
при форматировании объем памяти

| | |*0x10* |Ошибка выполнения +
криптографического преобразования

| | |*0x11* |Нарушение работоспособности (ошибка) аппаратной подсистемы
устройства

| | |*0x12* |Закончился ресурс ключей ГСЧ. +
Генерация случайных чисел более невозможна.

| | |*0x20* |Повреждение системной области памяти или микропрограммы
(ошибка CRC)

| | |*0x21* |Неустранимая ошибка в оперативной памяти. +
Токен сохранил контекст ошибки и отключился

| | |*0x22* |Критический износ EEPROM-памяти. +
Операция записи была отвергнута

| | |*0x30* a|
_Secure_ _Messaging:_

Требуется переоткрытие канала Secure Messaging +
(т.е. выработка новых KEK и CEK)

| | |*0x31* a|
_Secure_ _Messaging:_

Требуется выработать новый CEK +
(в рамках текущего канала SM)

| | |*0x32* a|
_Secure_ _Messaging:_

Не совпала имитовставка +
в составе защищенной SM APDU-команды

| | |*0x33* a|
_Secure_ _Messaging:_

Значение счетчика команды меньше, чем ожидается +
(но команда корректна)

| | |*0x34* a|
_Secure_ _Messaging:_

ID команды не соответствует ожидаемому +
(но команда корректна)

| | |*0x35* a|
_Secure_ _Messaging:_

Переоткрытие канала SM невозможно +
(еще не истек таймаут)

| | |*0x37* a|
_Secure_ _Messaging:_

При зашифровании APDU-ответа произошла фатальная ошибка

| | |*0x38* a|
_Secure_ _Messaging:_

Невозможно вернуть зашифрованный ответ +
(нет данных о значении Le)

| | |*0x39* a|
_Secure_ _Messaging:_

Не загружен ключ активации

| | |*0x3A* a|
_Secure_ _Messaging:_

Операция должна быть защищена SM +
(т.е. требуется защищенный канал) +
или вообще не может быть выполнена +
по бесконтактному интерфейсу

| | |*0x3F* a|
_Secure_ _Messaging:_

Отладочный код возврата. +
Об обстоятельствах его возникновения +
сообщать разработчикам SM

| | |*0x40* a|
_Мультиинтерфесные устройства:_

Эта команда не может быть выполнена +
по бесконтактному интерфейсу

| | |*0x50* a|
_Ошибка встроенной аппаратуры:_

Ошибка при входе в командный режим Bluetooth–модуля

| | |*0x51* a|
_Ошибка встроенной аппаратуры:_

Ошибка при установке текущих настроек Bluetooth–модуля

| | |*0x52* a|
_Ошибка встроенной аппаратуры:_

Ошибка при обмене с Apple–крипточипом

| | |*0x53* a|
_Ошибка встроенной аппаратуры:_

Аппаратная ошибка при установке интерфейса обмена. +
Интерфейс не был изменен

| | |*0x55* a|
_Ошибка встроенной аппаратуры:_

Ошибка при обмене с кнопкой +
(когда кнопка физически присутствует)

| | |*0x56* a|
_Ошибка встроенной аппаратуры:_

Ошибка инициализации RTC

| | |*0x57* a|
_Ошибка встроенной аппаратуры:_

Ошибка чтения/записи RTC

| | |*0x58* a|
_Ошибка встроенной аппаратуры:_

Дата/время не заданы

| | |*0x59* a|
_Ошибка встроенной аппаратуры:_

Дата/время искажены

| | |*0x83* |Обнаружено нарушение протокола обмена с токеном

| | |*0x84* |Токен занят обработкой другой команды

| | |*0x85* |В данной папке уже создано максимальное количество файловых
объектов. +
Создание нового файлового объекта невозможно

| | |*0x86* |Токен работает не с правами доступа «Гость». +
Перед выполнением аутентификации владельца +
требуется очистить права доступа +
командой RESET ACCESS RIGHTS

| | |*0x87* |Неверная контрольная сумма защищенного файлового объекта

| | |*0x88* |Слишком много локальных LogIn’ов +
(хранилище заполнено)

| | |*0x89* |Размер нового PIN-кода меньше минимально допустимого для
этого CHV-RSF

| | |*0x8A* |Журнал ошибочных операций токена переполнен. +
Основная функциональность токена заблокирована +
до момента очистки журнала либо +
до момента низкоуровневого форматирования токена

| | |*0x8B* |Необходимо задать или сменить +
аутентификационные данные

| | |*0x8C* |PIN-код не удовлетворяет всем текущим политикам качества. +
Операция не выполнена

| | |*0x8D* |PIN-код содержится в истории (недавно использовался). +
PIN-код не был изменен

| | |*0x90* |Ожидается транзакция с другим ID (КриптоПро ФКН)

| | |*0x91* |Исчерпан счетчик операций EKE (КриптоПро ФКН)

| | |*0x92* |Исчерпан счетчик операций подписи (КриптоПро ФКН)

| | |*0x93* |Исчерпан счетчик операций DH (КриптоПро ФКН)

| | |*0x94* |Исчерпан счетчик неуспешных операций (КриптоПро ФКН)

| | |*0x95* |Исчерпан счетчик последовательных +
неуспешных операций (вводов PINа EKE) (КриптоПро ФКН)

| | |*0xA0* |Неверное функционирование криптоалгоритма или ГСЧ, +
выявленное в процессе его реальной работы +
(а не при диагностике карты)

| | |*0xA1* a|
_Ошибка КриптоПро ФКН2:_

Контекст ФКН2 не сформирован

| | |*0xA2* a|
_Ошибка КриптоПро ФКН2:_

Контекст ФКН2 уже сформирован

| | |*0xA3* a|
_Ошибка КриптоПро ФКН2:_

Поиск контейнеров ФКН2 не инициирован

| | |*0xA4* a|
_Ошибка КриптоПро ФКН2:_

Нарушение ID транзакции

| | |*0xA5* a|
_Ошибка КриптоПро ФКН2:_

Попытка выполнить 2-й шаг аутентификации +
по EKE без выполнения 1-го шага

| | |*0xA6* a|
_Ошибка КриптоПро ФКН2:_

Попытка чтения текущего состояния SM, +
если SM-канал не открыт

| | |*0xA7* a|
_Ошибка КриптоПро ФКН2:_

Secure Messaging: формат пришедшей команды верен, +
однако имитовставка неправильная

| | |*0xA8* a|
_Ошибка КриптоПро ФКН2:_

Secure Messaging: нет поля New Le, +
невозможно вернуть защищенный ответ

| | |*0xA9* a|
_Ошибка КриптоПро ФКН2:_

Не поддерживается данный алгоритм +
аутентификации по EKE или для подписи

| | |*0xAA* a|
_Ошибка КриптоПро ФКН2:_

Токен не находится в режиме «белых» хеш-значений

| | |*0xAB* a|
_Ошибка КриптоПро ФКН2:_

Данное хеш-значение не найдено в списке «белых» +
(если на токене установлен режим «белых» хеш-значений)

| | |*0xAC* a|
_Ошибка КриптоПро ФКН2 (возвращается устройством-компаньоном):_

Команда была отвергнута устройством-компаньоном, +
т.к. не может быть послана извне

| | |*0xC0* a|
_Ошибка_ _Rutoken_ _ECP_ _touch:_

Операция не была подтверждена +
нажатием кнопки до истечения таймаута

| | |*0xC1* a|
_Ошибка Хранилищ:_

Создаваемый сертификат является копией +
уже загруженного в Хранилище

| | |*0xC2* a|
_Ошибка Хранилищ:_

Хранилище заполнено, +
нет возможности добавить новый объект

| | |*0xC3* a|
_Ошибка Хранилищ:_

Этот сертификат был ранее +
удален из Хранилища (помещен в список удаленных), +
повторное создание сертификата невозможно.

| | |*0xC4* a|
_Ошибка Хранилищ:_

Timestamp объекта содержит +
более раннюю отметку времени, +
чем у уже записанного в токене. +
Объект не может быть обновлен

| | |*0xC5* a|
_Ошибка Хранилищ:_

Нарушена контрольная сумма образа с ПО.

| | |*0xCC* a|
_Ошибка Хранилищ:_

Данное Хранилище отсутствует (не было сформировано) на токене

| | |*0xCD* a|
_Ошибка Хранилищ:_

Данное Хранилище уже сформировано, повторное создание невозможно

| | |*0xF0* |Отладочные коды возврата. +
Об обстоятельствах их возникновения +
просьба сообщать разработчикам

| | |*0xF1* |

| | |*0xF2* |
|===
====